version: "3.6"

services:
  rstudio:
    build: 
      context: ./
    container_name: rstudio
    restart: on-failure
    volumes:
      - ./src:/home/rstudio/src
    networks:
      - rankheat
    environment:
      - PASSWORD=rstudio1
      - DISABLE_AUTH=true
    ports:
      - 8852:8787

networks:
  rankheat:

volumes:
  r_libs_n: