version: "3.6"

services:
  shiny-server-1: &shiny-server
    build:
      dockerfile: Dockerfile.server
      context: .
    restart: always
    deploy:
      resources:
        limits:
          cpus: '2'
    networks:
      - rankheat
  shiny-server-2:
    <<: *shiny-server
  shiny-server-3:
    <<: *shiny-server
  shiny-server-4:
    <<: *shiny-server
  shiny-server-5:
    <<: *shiny-server
  traefik:
    restart: always
    image: traefik:v2.10
    environment:
      - LETS_ENCRYPT_EMAIL
    volumes:
      - ./traefik/traefik.yml:/traefik.yml
      - ./traefik/load-balancer.yml:/load-balancer.yml
      - ./traefik/letsencrypt:/letsencrypt
    networks:
      - rankheat
    command:
      - --certificatesresolvers.defaultresolver.acme.email=${LETS_ENCRYPT_EMAIL}
    depends_on:
      - shiny-server-1
    ports:
      - 80:80
      - 443:443

networks:
  rankheat:
