version: "3.6"

services:
  rstudio:
    build: 
      context: ./
    container_name: rstudio
    restart: on-failure
    volumes:
      - type: bind
        source: ./src
        target: /home/rstudio/src
      - type: volume
        source: r_libs_n
        target: /usr/local/lib/R
    networks:
      - rankheat
    environment:
      - PASSWORD=rstudio1
      - DISABLE_AUTH=true
    ports:
      - 8852:8787

networks:
  rankheat:

volumes:
  r_libs_n: