services:
  rstudio:
    build:
      context: ./
    container_name: rstudio
    restart: on-failure
    volumes:
      - ./rankheatplot:/home/rstudio/rankheatplot
    networks:
      - rankheat
    environment:
      - APP_ENV
      - DISABLE_AUTH=true
      - PASSWORD=rstudio1
      - PROJECT_ROOT
      - R_STUDIO_PORT
    ports:
      - ${R_STUDIO_PORT}:8787

networks:
  rankheat:

volumes:
  r_libs_n:
