http:
  routers:
    https_router:
      rule: "Host(`rankheatplot.com`)"
      service: backend
      tls:
        certResolver: defaultresolver
      middlewares:
        - redirectToSite

  services:
    backend:
      loadBalancer:
        servers:
          - url: "http://shiny-server-1:3838"
          - url: "http://shiny-server-2:3838"
          - url: "http://shiny-server-3:3838"
          - url: "http://shiny-server-4:3838"
          - url: "http://shiny-server-5:3838"
        sticky:
          cookie: {}

  middlewares:
    redirectToSite:
      redirectRegex:
        regex: "^https://([^/]+)/?$"
        replacement: "https://$1/rankheatplot/"
